name: apiverve_distancecalculator
description: Distance Calculator is a simple tool for calculating the distance between two locations. It returns the distance in miles and kilometers.
version: 1.1.14
homepage: https://apiverve.com/marketplace/distancecalculator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/distancecalculator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
